services:
  jenkins:
    build:
      context: ./jenkins-setup
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home # Persist Jenkins data
      - ./jenkins-setup/plugins.txt:/usr/share/jenkins/ref/plugins.txt # Auto-install plugins
      - ./jenkins-setup/scripts:/usr/share/jenkins/ref/init.groovy.d # Groovy scripts for initial setup
      - /var/run/docker.sock:/var/run/docker.sock # Access to Docker from Jenkins

  flask_app:
    build:
      context: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

volumes:
  jenkins_home: # Volume for Jenkins data persistence
